export const theme = {
  colors: {
    bg: '#0e0e10',
    surface: '#151517',
    surfaceAlt: '#1d1d20',
    border: '#26262a',
    borderStrong: '#37373c',
    text: '#ededef',
    textMuted: '#9b9ba3',
    textDim: '#6b6b72',
    accent: '#ededef',
    accentHover: '#ffffff',
    link: '#8cb4ff',
    success: '#4ade80',
    warning: '#fbbf24',
    danger: '#f87171',
    info: '#60a5fa',
  },
  radius: { sm: '6px', md: '8px', lg: '12px', pill: '999px' },
  spacing: (n) => `${n * 4}px`,
  shadow: {
    sm: '0 1px 2px rgba(0,0,0,.2)',
    md: '0 4px 12px rgba(0,0,0,.3)',
    lg: '0 16px 48px rgba(0,0,0,.5)',
  },
  font: {
    body: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, sans-serif',
    mono: 'ui-monospace, "SF Mono", Menlo, monospace',
  },
  transition: '120ms ease',
};
